### ISSUE TITLE
Many timeouts

### ISSUE THREAD

**Issue by alex88** [Vestorly/ember-cli-s3-sync#20]
Hi there,

I'm using s3 sync as a CI step in circleci, I've seen that many times the sync goes in timeout:

```
     ... other files ...
     path: '/home/ubuntu/project/dist/fonts/fontawesome-webfont.woff',
     fd: null,
     flags: 'r',
     mode: 438,
     start: undefined,
     end: undefined,
     autoClose: true,
     pos: undefined,
     destroyed: true,
     closed: true },
  Bucket: 'my-bucket' })
Upload complete: /home/ubuntu/project/dist/fonts/fontawesome-webfont.woff
```

I'm not sure that's the last file, have you ever had issues like this?

**Comment by joebartels** [comment]
@alex88 it's rare but I've also seen timeouts in circleCI (and deploying locally).  When this happens locally i just re-run with `--skip-build` flag. 
It's helpful to know that others have similar issue. It's never been blocking for me enough to investigate but now that you've brought it up as well I'm gonna take a closer look at the async code that wraps the aws-sdk's `putObject`

again, thanks for reporting!

**Comment by alex88** [comment]
Maybe just make a configurable timeout (any frontend file uploads shouldn't take more than a few seconds with a server-server connections) and in that case restart the upload for n times

**Comment by joebartels** [comment]
@alex88 good thoughts. I like that idea. The other idea i'll be playing with is reducing the concurrency from 2, to 1 for the async `putObject` that uploads the assets.  I'll have some time this week to try these both out.

**Comment by alex88** [comment]
Count me in for beta testing :wink:

**Comment by joebartels** [comment]
i logged feature request in this issue, https://github.com/Vestorly/ember-cli-s3-sync/issues/22
@alex88 please reopen if still seeing issue after: PR https://github.com/Vestorly/ember-cli-s3-sync/pull/21 (v0.0.9)

**Comment by alex88** [comment]
@joebartels awesome! thanks!

**Comment by alex88** [comment]
@joebartels first deploy after upgrading, timeout :smiley: Anyway, I'll wait for PR #22 to be able to set a small timeout

**Comment by joebartels** [comment]
dangit. you're not on dial up are you :trollface: 
i'll get that feature in as soon as i can -really appreciate the feedback!

**Comment by joebartels** [comment]
@alex88 one thing to try is running with verbose logging: 
https://github.com/Vestorly/ember-cli-s3-sync#ember-cli-s3-sync-options
If the aws-sdk logs anything useful that could help pin down the nature of issue.

**Comment by alex88** [comment]
@joebartels nope! It's in circleci's deployment stage, I think they're on ec2!
Anyway, seems there is no verbose logging option, anyway, AWS sdk already have a timeout of 2 minutes and retries, timeout happens after 10 minutes of no console output in circleci, damn strange!
It should at least retry a couple times

**Comment by alex88** [comment]
But, sometimes I got timeouts even after only one file being uploaded, so it should be something in the upload part, not anything around it

**Comment by joebartels** [comment]
@alex88 i removed [async](https://github.com/caolan/async) library in favor of manually chaining the file uploads. A timeout was also added, hardcoded to 30 seconds (for now). The file name of the unresponsive upload will be printed to console (previously only completed uploads were getting printed to console). I'm hoping now that when the upload process goes unresponsive we might be able to find a pattern or set of problem files.

Next step is https://github.com/Vestorly/ember-cli-s3-sync/issues/22 to make the timeout configurable, skipping that particular upload and checking later whether it's completed -re-trying again if it hasn't

**Comment by alex88** [comment]
@joebartels since 0.0.10, no timeouts, great job! I'll write here in case we'll get further problems
